### ISSUE TITLE
Joi?

### ISSUE THREAD

**Issue by amcdnl** [PLEEROCK/validator.ts#2]
Joi support would be cool :)

**Comment by PLEEROCK** [comment]
validation in this library is *decorator* based, validation principle in joi a bit differ. How exactly do you want to see validation using joi in this library, or maybe you want to have some specific validation types from joi library?

**Comment by amcdnl** [comment]
Forgot to mention, love your microframework libraries, I was actually doing the EXACT same thing in my project.  Heres what I came up with ( I wasn't using TS til recently so its babelish ).

**FormModel**
```
export class FormModel extends Base {

  static type = 'FormModel';

  static schema = {
    name: Joi.string().alphanum().required(),
    id: Joi.objectId(),
    disabled: Joi.boolean(),
    description: Joi.string().max(200),
    acronym: Joi.string().min(2).max(4)
  };

  constructor(model){
    super(model);
  }

}
```

** BaseModel **
```
import { Joi } from '../common/validate';

export class Base {
  
  static schema: Object;

  constructor(model){
    Object.assign(this, model);
  }

  /**
   * Validates the object
   * @return {Object} error validation from joi
   */
  static isValid(m) {
    return Joi.validate(m, this.schema);
  }

  /**
   * Returns the raw types for the given schema definitions
   * Use it like: `console.log(Form.types)`
   * 
   * @return {Object} key/value pair of types
   */
  static get types(){
    let schema = this.schema,
        types = {};

    for(let t in schema){
      const sch = schema[t];
      let desc = sch.describe();

      if(desc.meta){
        for(let meta of desc.meta){
          if(meta.type) types[t] = meta.type;
        }
      }

      if(!types[t]){
        types[t] = desc.type;
      }
    }

    return types;
  }

}
```

so in typescript world it would look something like this:

```
export class Form extends Base {

  @validate(Joi.string().alphanum().required())
  name: string;

}
```

**Comment by PLEEROCK** [comment]
Thanks, Im glad that people doing things the same way as me.

What is the benefit of using Joi?
Isn't what you are trying to do with Join can't be achieved right now?

```typescript
  @validate(Joi.string().alphanum().required())
```
Probably can be done this way:
```typescript
export class Form extends Base {

  @ToString()
  @IsAlphanumeric()
  @NotEmpty()
  name: string;

}
```
Also it looks like such expressions: `@validate(Joi.string().alphanum().required())` can grow and look ugly and complicated in decorator which should be simple.
However, if joi has some validation functionality which does not exist in this library, this can be added.

**Comment by amcdnl** [comment]
No, this could be done easily, I just need to make a decorate call function for it. I'll probably do that later today even. We can discuss more after I finish and I'll post a gist.

Um, ya, I suppose it could be done like that. That might be a good idea but what about order matters, I'm not sure how detailed you can get w/ decorators regarding order.

You are correct, it could get pretty ugly but its Fluent syntax. Its no different that jquery chaining. Joi is BY FAR the most popular validation framework and has more features than validator.js does too. ( I've done a ton of research on this in the past week ).

**Comment by PLEEROCK** [comment]
validator.js is the most popular (5k stars on github), that's why I choose it. But its not feature rich. I'm planning to add all missing features by the time. Already added few that I needed.

**Comment by amcdnl** [comment]
It is more popular in terms of GHS, but I was looking at this: http://www.screencast.com/t/z6jKThhAogS

**Comment by amcdnl** [comment]
I fold, after reviewing your stuff and joi, a lot of the things that are there aren't needed or could be added easily with extensions. Thanks for humoring me on the subject.
