### ISSUE TITLE
Cannot find module 'validator.ts/Validator'

### ISSUE THREAD

**Issue by imperugo** [pleerock/validator.ts#6]
Hi, 
I'm trying to use your library but I'm getting a strange compilation error.

Basically the compilation output message is [Cannot find module 'validator.ts/Validator'](url) for all files that have `import * as Validator from "validator.ts/Validator";`

All packages look in the right place and VSCode offers me the intellisense for your package, but the compilation doesn't work.

Any hint?
Thx

**Comment by imperugo** [comment]
I think I've found the reason of that error.
addind node_modules path to TSFiles (gulp) seems to be ok

```javascript
var tsFiles = ["typings/main.d.ts", 
					"typings/main/**/*.d.ts", 
					"node_modeuls/**/*.d.ts",
					"src/**/*.ts"];
var source = gulp.src(tsFiles);
```

Does it make sense for you?

**Comment by pleerock** [comment]
Hello,
from what I see from the gulp-typescript docs that when you are using `noExternalResolve` you must specify everything you use, including libraries (like validator) from `node_modules`. This means that if you are excluding node_modules those modules will not be included, which is pointless until you are going to specify each file in your options, and makes using of this option useless. So I dont recommend to use it.

**Comment by imperugo** [comment]
Got it.

Thanks
